/**
 * Emits monolithic JSON, per-date JSON shards, passengerDates.json, hourly summary,
 * and src/generated/passengerDataIndex.ts for static Metro requires.
 */
import fs from 'fs';
import path from 'path';

export type EmitRow = {
  tarih: string;
  durakId: string;
  durakAd: string;
  saat: number;
  yolcuSayisi: number;
};

const INDEX_FILE = path.join('src', 'generated', 'passengerDataIndex.ts');

export function emitPassengerDataArtifacts(
  out: EmitRow[],
  projectRoot: string
): { dates: string[]; byDateCount: number } {
  if (!out.length) {
    throw new Error('emitPassengerDataArtifacts: empty input');
  }

  const outDir = path.join(projectRoot, 'assets', 'data');
  const byDateDir = path.join(outDir, 'passenger-by-date');
  const outFile = path.join(outDir, 'passengerData.json');
  const datesFile = path.join(outDir, 'passengerDates.json');
  const hourlyFile = path.join(outDir, 'hourlyStationSummary.json');
  const indexPath = path.join(projectRoot, INDEX_FILE);

  fs.mkdirSync(byDateDir, { recursive: true });
  fs.mkdirSync(path.dirname(indexPath), { recursive: true });

  const byTarih = new Map<string, EmitRow[]>();
  for (const r of out) {
    const list = byTarih.get(r.tarih) ?? [];
    list.push(r);
    byTarih.set(r.tarih, list);
  }

  const dates = [...byTarih.keys()].sort();
  for (const d of dates) {
    const dayRows = byTarih.get(d) ?? [];
    const dayPath = path.join(byDateDir, `${d}.json`);
    fs.writeFileSync(dayPath, JSON.stringify(dayRows, null, 2), 'utf8');
  }

  const hourly: { durakId: string; tarih: string; saat: number; yolcuSayisi: number }[] = out.map(
    (r) => ({
      durakId: r.durakId,
      tarih: r.tarih,
      saat: r.saat,
      yolcuSayisi: r.yolcuSayisi,
    })
  );

  fs.writeFileSync(outFile, JSON.stringify(out, null, 2), 'utf8');
  fs.writeFileSync(datesFile, JSON.stringify(dates, null, 2) + '\n', 'utf8');
  fs.writeFileSync(hourlyFile, JSON.stringify(hourly, null, 2), 'utf8');

  const lines: string[] = [
    '/** Auto-generated by scripts/emitPassengerDataArtifacts / convertExcelToJson. Do not edit. */',
    "import type { PassengerRow } from '../types';",
    '',
    'type Loader = () => PassengerRow[];',
    '',
    'export const passengerDataLoaders: Record<string, Loader> = {',
  ];
  for (const d of dates) {
    lines.push(`  '${d}': () => require('../../assets/data/passenger-by-date/${d}.json') as PassengerRow[],`);
  }
  lines.push('};', '');

  fs.writeFileSync(indexPath, lines.join('\n') + '\n', 'utf8');

  return { dates, byDateCount: byTarih.size };
}
